const no_me_interesa_variantes = [
  "no, gracias",
  "no gracias",
  "te agradezco pero no",
  "no me interesa",
  "no me interesa en absoluto",
  "no me interesa para nada",
  "no me interesa en este momento",
  "no me llama la atención",
  "no me parece interesante",
  "no me resulta interesante",
  "no tengo interés",
  "no tengo interés en esto",
  "no tengo interés ahora",
  "no encuentro valor en esto",
  "no estoy interesado",
  "no estoy interesada",
  "no estoy interesado en esto",
  "no estoy interesada en esto",
  "no estoy interesado en lo que ofreces",
  "no estoy interesada en lo que ofreces",
  "no estoy interesado en este momento",
  "no estoy interesada en este momento",
  "no es de mi interés",
  "no es de mi interés ahora",
  "no tengo ningún interés",
  "no estoy para esto",
  "no quiero seguir adelante",
  "no quiero continuar",
  "por el momento no",
  "no quiero explorar esto",
  "no quiero participar",
  "no deseo participar",
  "no me resulta útil",
  "no necesitamos",
  "no necesitamos esto",
  "no necesitamos en este momento",
  "no necesitamos ahora",
  "no necesito",
  "no necesito esto",
  "no necesito en este momento",
  "no necesito ahora",
  "no estoy buscando",
  "no estoy buscando esto",
  "no estamos buscando",
  "no estamos buscando esto",
  "no estoy en búsqueda",
  "no estoy en búsqueda de esto",
  "no estamos en búsqueda",
  "no estamos en búsqueda de esto",
  "no estoy en necesidad de esto",
  "no estamos en necesidad de esto",
  "no requiero esto",
  "no requerimos esto",
  "no preciso esto",
  "no precisamos esto",
  "no estoy requiriendo esto",
  "no estamos requiriendo esto",
  "no estoy precisando esto",
  "no estamos precisando esto",
  "no estoy interesado en comprar",
  "no estoy interesado en adquirir",
  "no estoy interesada en comprar",
  "no estoy interesada en adquirir",
  "no estoy considerando esto",
  "no estamos considerando esto",
  "no me es necesario",
  "no nos es necesario",
  "no veo la necesidad",
  "no vemos la necesidad",
  "no estoy interesado en añadir",
  "no estoy interesada en añadir",
  "no estoy buscando añadir",
  "no estamos buscando añadir",
];

module.exports = { no_me_interesa_variantes };
