const no_me_interesa_variantes = [
  "no, gracias",
  "no gracias",
  "te agradezco pero no",
  "no me interesa",
  "no me interesa en absoluto",
  "no me interesa para nada",
  "no me interesa en este momento",
  "no me llama la atención",
  "no me parece interesante",
  "no me resulta interesante",
  "no tengo interés",
  "no tengo interés en esto",
  "no tengo interés ahora",
  "no encuentro valor en esto",
  "no estoy interesado",
  "no estoy interesada",
  "no estoy interesado en esto",
  "no estoy interesada en esto",
  "no estoy interesado en lo que ofreces",
  "no estoy interesada en lo que ofreces",
  "no estoy interesado en este momento",
  "no estoy interesada en este momento",
  "no es de mi interés",
  "no es de mi interés ahora",
  "no tengo ningún interés",
  "no estoy para esto",
  "no quiero seguir adelante",
  "no quiero continuar",
  "por el momento no",
  "no quiero explorar esto",
  "no quiero participar",
  "no deseo participar",
  "no me resulta útil",
  "no necesitamos",
  "no necesitamos esto",
  "no necesitamos en este momento",
  "no necesitamos ahora",
  "no necesito",
  "no necesito esto",
  "no necesito en este momento",
  "no necesito ahora",
  "no estoy buscando",
  "no estoy buscando esto",
  "no estamos buscando",
  "no estamos buscando esto",
  "no estoy en búsqueda",
  "no estoy en búsqueda de esto",
  "no estamos en búsqueda",
  "no estamos en búsqueda de esto",
  "no estoy en necesidad de esto",
  "no estamos en necesidad de esto",
  "no requiero esto",
  "no requerimos esto",
  "no preciso esto",
  "no precisamos esto",
  "no estoy requiriendo esto",
  "no estamos requiriendo esto",
  "no estoy precisando esto",
  "no estamos precisando esto",
  "no estoy interesado en comprar",
  "no estoy interesado en adquirir",
  "no estoy interesada en comprar",
  "no estoy interesada en adquirir",
  "no estoy considerando esto",
  "no estamos considerando esto",
  "no me es necesario",
  "no nos es necesario",
  "no veo la necesidad",
  "no vemos la necesidad",
  "no estoy interesado en añadir",
  "no estoy interesada en añadir",
  "no estoy buscando añadir",
  "no estamos buscando añadir",
  "no tengo necesidad",
  "no tenemos necesidad",
  "no tengo la necesidad",
  "no tenemos la necesidad",
  "no tengo esta prioridad",
  "no tenemos esta prioridad",
  "no es prioridad para mí",
  "no es prioridad para nosotros",
  "no está dentro de mis prioridades",
  "no está dentro de nuestras prioridades",
  "no tengo esta prioridad",
  "no tenemos esta prioridad",
  "no es prioridad ahora",
  "no es la prioridad",
  "lo estamos manejando inhouse",
  "lo manejamos internamente",
  "lo hacemos inhouse",
  "lo hacemos internamente",
  "no necesitamos",
  "no estamos interesados en externalizar",
  "lo estamos gestionando inhouse",
  "lo gestionamos internamente",
  "no es nuestra prioridad",
  "no es mi prioridad",
  "no es prioridad en este momento",
  "no es nuestra prioridad en este momento",
  "no es mi prioridad en este momento",
  "no es una prioridad para nosotros",
  "no es una prioridad para mí",
  "no está en nuestras prioridades",
  "no está en mis prioridades",
  "no está en nuestra lista de prioridades",
  "no está en mi lista de prioridades",
  "no es una prioridad ahora",
  "no es una prioridad en este momento",
  "en este momento no es una prioridad",
  "ahora no es una prioridad",
  "por ahora no es prioridad",
  "por ahora no es prioridad para nosotros",
  "por ahora no es prioridad para mí",
  "por el momento no es prioridad",
  "por el momento no es prioridad para nosotros",
  "por el momento no es prioridad para mí",
  "lo estamos manejando inhouse",
  "lo manejamos internamente",
  "lo hacemos inhouse",
  "lo hacemos internamente",
  "no necesitamos",
  "no estamos interesados en externalizar",
  "lo estamos gestionando inhouse",
  "lo gestionamos internamente",
  "ya tenemos un equipo",
  "ya tenemos quien se encargue de eso",
  "ya tenemos a alguien que se encargue",
  "tenemos un equipo interno",
  "tenemos personal para eso",
  "tenemos un equipo para eso",
  "tenemos a alguien que lo maneja",
  "nuestro equipo se encarga de eso",
  "nuestro personal se encarga de eso",
  "no buscamos externalizar",
  "no buscamos subcontratar",
  "eso lo hacemos nosotros",
  "eso lo manejamos nosotros",
  "ya lo hacemos nosotros",
  "ya está cubierto internamente",
  "ya está gestionado internamente",
  "ya está manejado internamente",
  "no necesitamos ayuda con eso",
  "no necesitamos soporte externo",
  "no requerimos servicios externos",
  "lo hacemos por nuestra cuenta",
  "lo gestionamos nosotros mismos",
  "lo manejamos nosotros mismos",
  "tenemos un buen equipo",
  "tenemos un buen equipo",
  "contamos con un buen equipo",
  "poseemos un buen equipo",
  "disponemos de un buen equipo",
  "tenemos un equipo sólido",
  "contamos con un equipo sólido",
  "poseemos un equipo sólido",
  "disponemos de un equipo sólido",
  "tenemos un equipo fuerte",
  "contamos con un equipo fuerte",
  "poseemos un equipo fuerte",
  "disponemos de un equipo fuerte",
  "tenemos un equipo excelente",
  "contamos con un equipo excelente",
  "poseemos un equipo excelente",
  "disponemos de un equipo excelente",
  "tenemos un equipo competente",
  "contamos con un equipo competente",
  "poseemos un equipo competente",
  "disponemos de un equipo competente",
  "tenemos un equipo calificado",
  "contamos con un equipo calificado",
  "poseemos un equipo calificado",
  "disponemos de un equipo calificado",
  "tenemos un equipo experimentado",
  "contamos con un equipo experimentado",
  "poseemos un equipo experimentado",
  "disponemos de un equipo experimentado",
  "tenemos un equipo profesional",
  "contamos con un equipo profesional",
  "poseemos un equipo profesional",
  "disponemos de un equipo profesional",
  "tenemos un equipo especializado",
  "contamos con un equipo especializado",
  "poseemos un equipo especializado",
  "disponemos de un equipo especializado",
  "tenemos un equipo capacitado",
  "contamos con un equipo capacitado",
  "poseemos un equipo capacitado",
  "disponemos de un equipo capacitado",
  "tenemos un equipo eficiente",
  "contamos con un equipo eficiente",
  "poseemos un equipo eficiente",
  "disponemos de un equipo eficiente",
  "tenemos un equipo de alta calidad",
  "contamos con un equipo de alta calidad",
  "poseemos un equipo de alta calidad",
  "disponemos de un equipo de alta calidad",
  "tenemos un equipo destacado",
  "contamos con un equipo destacado",
  "poseemos un equipo destacado",
  "disponemos de un equipo destacado",
  "tenemos un equipo talentoso",
  "contamos con un equipo talentoso",
  "poseemos un equipo talentoso",
  "disponemos de un equipo talentoso",
  "lo hacemos de manera interna",
  "lo tenemos cubierto internamente",
  "tenemos a alguien interno para eso",
  "lo tenemos resuelto internamente",
  "uno de los socios es",
  "un experto en",
  "su equipo se ocupa de",
  "nosotros lo gestionamos",
  "nosotros nos ocupamos de eso",
  "ya tenemos a alguien",
  "ya tenemos quien lo maneje",
  "nos encargamos internamente",
  "lo gestionamos con nuestro equipo",
  "tenemos un socio que",
  "nos ocupamos con nuestro personal",
  "equipo propio",
  "tenemos a alguien en nuestro equipo",
  "nos encargamos internamente con nuestro equipo",
  "somos autosuficientes",
  "nos encargamos de esos temas internamente",
  "precisamente se ocupa de los temas que me mencionas",
  "exactamente se encarga de los asuntos que mencionas",
  "se encarga específicamente de los aspectos que indicas",
  "es responsable de los temas mencionados",
  "maneja específicamente los asuntos indicados",
  "se dedica a las cuestiones que mencionas",
  "se ocupa directamente de las áreas que mencionas",
  "e encarga de los puntos que mencionas",
  "se responsabiliza de los temas en cuestión",
  "se enfoca en las cuestiones tratadas",
];

module.exports = { no_me_interesa_variantes };
