const propuesta_palabras_clave = [
  "ayudar",
  "ayudo",
  "ayudamos",
  "ayudarte",
  "ayudaremos",
  "propuesta",
  "proposición",
  "interesar",
  "interés",
  "interesado",
  "acompañar",
  "acompaño",
  "acompañamos",
  "acompañarte",
  "acompañaremos",
  "charlar",
  "charla",
  "charlemos",
  "conversar",
  "conversación",
  "platicar",
  "plática",
  "hablar",
  "hablemos",
  "hablamos",
  "hablaremos",
  "platiquemos",
  "platicamos",
  "platicaremos",
  "colaborar",
  "colaboración",
  "colaboramos",
  "colaboraré",
  "colaboraremos",
  "asistir",
  "asistencia",
  "asistimos",
  "asistiré",
  "asistiremos",
  "soporte",
  "apoyo",
  "apoyamos",
  "apoyar",
  "apoyaré",
  "apoyaremos",
  "apoyarte",
  "consulta",
  "diagnóstico",
  "diagnosticar",
  "diagnosticaremos",
  "resultados",
  "metodología",
  "potenciar",
  "seguridad psicológica",
  "acciones efectivas",
  "rendimiento",
  "crecer",
  "crecimiento",
  "cierre de ventas",
  "venta",
  "ventas",
  "mejora",
  "mejorar",
  "optimizamos",
  "optimizar",
  "reducir costos",
  "aumentar ingresos",
  "ingresos",
  "costos",
  "ahorro",
  "eficiencia",
  "escala",
  "escalar",
  "consultoría",
  "consultor",
  "asesoría",
  "asesorar",
  "consultores",
  "solución",
  "soluciones",
  "beneficio",
  "beneficios",
  "oportunidad",
  "sistema de captación",
  "captación de clientes",
  "captar clientes",
  "clientes potenciales",
  "sinergia",
  "sinergias",
  "sinérgico",
  "impacto",
  "impactar",
  "proceso",
  "procesos",
  "proceso interno",
  "internos",
  "gestión",
  "gestionar",
  "gestión de recursos humanos",
  "diagnóstico preliminar",
  "identificar desafíos",
  "estrategia actual",
  "metodología personalizada",
  "productividad",
  "relaciones",
  "relaciones a largo plazo",
  "lograr objetivos",
  "objetivos",
  "relaciones desgastadas",
  "reducir rotación",
  "reducir rotación de talento",
  "optimizar procesos",
  "fortalecer equipos",
  "coaching",
  "potencial",
  "máximo potencial",
  "proceso de venta",
  "mejorar resultados",
  "mejorar ingresos",
  "construcción de funnels",
  "funnels de ventas",
  "cerrar ventas",
  "ventas efectivas",
  "estrategia de ventas",
  "técnicas de ventas",
  "herramientas de ventas",
  "ventas consultivas",
  "ventas estratégicas",
  "reunión",
  "agendar reunión",
  "reunión virtual",
  "reunión presencial",
  "llamada",
  "call",
  "videollamada",
  "videoconferencia",
  "demo",
  "demostración",
  "sesión",
  "agendar",
  "cita",
  "programar una reunión",
  "invitar a reunión",
  "organizar una llamada",
  "coordinamos una llamada",
  "agenda",
  "programemos una reunión",
];

module.exports = { propuesta_palabras_clave };
