const palabrasClaveReunion = [
    "reunión",
    "agendar reunión",
    "reunión virtual",
    "reunión presencial",
    "llamada",
    "call",
    "videollamada",
    "videoconferencia",
    "demo",
    "demostración",
    "sesión",
    "agendar",
    "cita",
    "programar una reunión",
    "invitar a reunión",
    "organizar una llamada",
    "coordinamos una llamada",
    "agenda",
    "programemos una reunión",
    "charlar",
    "charlemos",
    "hablar",
    "hablemos",
    "platicar",
    "platiquemos",
    "15 minutos",
    "20 minutos",
    "media hora",
    "30 minutos",
    "una hora",
    "60 minutos",
    "hablamos la próxima semana",
    "hablamos esta semana",
    "hablemos la próxima semana",
    "hablemos esta semana",
    "la próxima semana",
    "esta semana",
    "nos reunimos la próxima semana",
    "nos reunimos esta semana",
    "conversamos la próxima semana",
    "conversamos esta semana",
    "reunámonos",
    "juntémonos",
    "conectémonos",
    "conversemos",
    "nos reunimos",
    "nos juntemos",
    "nos conectemos",
    "nos hablamos",
    "nos charlamos",
    "conversar",
    "conversemos",
    "charlemos",
    "reunámonos",
    "juntémonos",
    "conectémonos",
  ];

  module.exports = { palabrasClaveReunion };
